### PR TITLE
Added print funciton to show genres for movies and books

### PR DESCRIPTION
**Pull request by jacbart**
Also edited the readme file to look pretty and so jacbart as a contributer. there is still a few differences but at least it is less. you will also have to recompile it.

### CODE REVIEW

**Comment by cpcharland** [comment]
For the life of me i can not get this to merge

**Comment by jacbart** [comment]
all you do it follow the instcutions. click on the blue link and after you merge you need to go into the files that were changed and delete the differences. it will say the differences by having ">>>>>>>head" as what you had and some random code like ">>>>>>9er738769jdhsdjh" that to show what I put. just delete what you dont want and then push it.

**Comment by jacbart** [comment]
there is probably some youtube videos on how to do it.

**Comment by cpcharland** [comment]
Got it

**Pull request merged**
