### PR TITLE
Added print function to show genres for movies and books

### PR DESCRIPTION
**Pull request by jacbart**
Also added a Makefile for easier compiling, and edited the readme file.The reason for so many additions and deletion is because It would not let me compile unless I changed the spaces to tabs, I don't know why.

### CODE REVIEW

**Comment by jacbart** [comment]
if there is too much i can redo so that all it changes are the function that i add and nothing else

**Comment by cpcharland** [comment]
I'm not sure how to merge this yet but ill do it when I get a chance

**Comment by jacbart** [comment]
it is pretty simple just follow the instruction that it gives but you will have to go into the code and delete the differences it does not do it automatically. it would be easier if you reject this and i will resubmit an easier one to merge

**Comment by cpcharland** [comment]
Ok

**Pull request closed without merging**
